import time

from selenium.webdriver.common.by import By
from Config.config import Testdata
from Pages.BasePage import BasePage

#ADDNEW="/html/body/app-root/body/profile/div/mat-tab-group/div/mat-tab-body[4]/div/transfer/div/div/div[2]/div[2]/button"



class Tranferprofile(BasePage):
    PROFILEBUTTON = (By.XPATH, '//a[@href="/profile"]')
    TRANFERTABBUTTON = (By.XPATH, '//mat-tab-group/mat-tab-header/div[2]/div/div/div[4]')
    ADDNEW = (By.XPATH, "/html/body/app-root/body/profile/div/mat-tab-group/div/mat-tab-body[4]/div/transfer/div/div/div[2]/div[2]/button")
    PROFILENAME = (By.XPATH, "//*[@Placeholder='Profile Name']")
    OVERWRITE = (By.XPATH, "/html/body/app-root/body/profile/div/mat-tab-group/div/mat-tab-body[4]/div/transfer/div/div/div[3]/mat-accordion/mat-expansion-panel[1]/div/div/mat-form-field[2]/div/div[1]/div/mat-select")
    OVERWRITEVALUE = (By.XPATH, "//*[@Value='1']")
    REMARK = (By.XPATH, "//*[@Placeholder='Remarks (optional)']")
    VALIDPREFIX = (By.XPATH, "//*[@Placeholder='Valid Prefix (optional)']")
    VALIDEXTENTION = (By.XPATH, "//*[@Placeholder='Valid Extension (optional)']")
    CHECKFILEMODIFICATION = (By.XPATH, "//*[@Placeholder='Check File Modification']")
    TRANFERVALIDATION = (By.XPATH,"//transfer/div/div/div[3]/mat-accordion/mat-expansion-panel[2]/mat-expansion-panel-header")
    VERIFYCHECKSUM = (By.XPATH, "//*[@Placeholder='Verify Checksum']")
    VERIFYCHECKSUMVALUE = (By.XPATH, "//*[@Value='1']")
    VERIFYCHECKSUMVALUE_TWO = (By.XPATH, "//*[@Value='0']")
    CHECKSUM = (By.XPATH, "//*[@Placeholder='Checksum']")
    CHECKSUMVALUE = (By.XPATH, "/html/body/div[3]/div[2]/div/div/mat-option[1]")
    TRANSFERFAIL = (By.XPATH, "//*[@Placeholder='Transfer Fail']")
    TRANSFERFAILVALUE = (By.XPATH, "/html/body/div[3]/div[2]/div/div/mat-option[1]")
    TRANSFERFAIL_VALUE = (By.XPATH, "//*[@Placeholder='Transfer Fail Value']")
    RETRYWAITTIME = (By.XPATH, "//*[@Placeholder='Retry Wait Time(min)']")
    DELETEAFTERFAILER = (By.XPATH, "//*[@Placeholder='Delete After Failure']")
    DELETEAFTERFAILERVALUE = (By.XPATH, "/html/body/div[3]/div[2]/div/div/mat-option[1]")
    TRANSFERMEC = (By.XPATH, "//transfer/div/div/div[3]/mat-accordion/mat-expansion-panel[3]/mat-expansion-panel-header")
    TRANSFERPROTOCOL = (By.XPATH, "//*[@Placeholder='Transfer Protocol']")
    TRANSFERPROTOCOLVALUE = (By.XPATH, "/html/body/div[3]/div[2]/div/div/mat-option[2]")
    OPERATIONTYPE = (By.XPATH, "//*[@Placeholder='Operation Type']")
    OPERATIONTYPEVALUE = (By.XPATH, "/html/body/div[3]/div[2]/div/div/mat-option[2]")
    DOWNLOADSPEED = (By.XPATH, "//*[@Placeholder='Download Speed(Mb/s)']")
    UPLOADSPEED = (By.XPATH, "//*[@Placeholder='Upload Speed(Mb/s)']")
    SAVEBUTON = (By.XPATH, "//mat-tab-group/div/mat-tab-body[4]/div/transfer/div/div/div[3]/div/button[1]")
    # TRANSFERMEC
    ALERT_MESSAGE = (By.XPATH, "/html/body/div[3]/div/div/snack-bar-container/simple-snack-bar/span")
    UPDATEDATA=(By.XPATH,"//transfer/div/div/div[2]/div[1]/table/tbody/tr/td[normalize-space(text())='automationtesting']")
    UPDATEDATA_NEW=(By.XPATH,"//transfer/div/div/div[2]/div[1]/table/tbody/tr/td[normalize-space(text())='automationtestingupdate']")
    UPDATEDATA_BUTTON=(By.XPATH,"//transfer/div/div/div[3]/div/button[1]")
    DELETEBUTTON = (By.XPATH,"//transfer/div/div/div[2]/div[1]/table/tbody/tr/td[normalize-space(text())='automationtestingupdate']/following-sibling::td/button")
    YESBUTTON=(By.XPATH,"//transfer-dialog-delete/div[2]/button[2]")
    
    def add_tranferprofile_withoutprofilename(self,PROFILENWME):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)
    
    def add_tranferprofile_withprofilename(self,PROFILENWME):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_send_keys(self.PROFILENAME,PROFILENWME)
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)
        
    def add_tranferprofile_withoutchecksumverfiy(self,profilename,remark,validprfix,validextention,clickmodification):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_send_keys(self.PROFILENAME,profilename)
        self.do_click(self.OVERWRITE)
        self.do_click(self.OVERWRITEVALUE)
        self.do_send_keys(self.REMARK,remark)
        self.do_send_keys(self.VALIDPREFIX,validprfix)
        self.do_send_keys(self.VALIDEXTENTION,validextention)
        self.do_send_keys(self.CHECKFILEMODIFICATION,clickmodification)
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)
        
    def add_tranferprofile_withchecksumverfiy(self,profilename,remark,validprfix,validextention,clickmodification):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_send_keys(self.PROFILENAME,profilename)
        self.do_click(self.OVERWRITE)
        self.do_click(self.OVERWRITEVALUE)
        self.do_send_keys(self.REMARK,remark)
        self.do_send_keys(self.VALIDPREFIX,validprfix)
        self.do_send_keys(self.VALIDEXTENTION,validextention)
        self.do_send_keys(self.CHECKFILEMODIFICATION,clickmodification)
        self.do_click(self.TRANFERVALIDATION)
        self.do_click(self.VERIFYCHECKSUM)
        self.do_click(self.VERIFYCHECKSUMVALUE)
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)
    
    def add_tranferprofile_withchecksumverfiy_disable(self,profilename,remark,validprfix,validextention,clickmodification):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_send_keys(self.PROFILENAME,profilename)
        self.do_click(self.OVERWRITE)
        self.do_click(self.OVERWRITEVALUE)
        self.do_send_keys(self.REMARK,remark)
        self.do_send_keys(self.VALIDPREFIX,validprfix)
        self.do_send_keys(self.VALIDEXTENTION,validextention)
        self.do_send_keys(self.CHECKFILEMODIFICATION,clickmodification)
        self.do_click(self.TRANFERVALIDATION)
        self.do_click(self.VERIFYCHECKSUM)
        self.do_click(self.VERIFYCHECKSUMVALUE_TWO)
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)
        
    def add_tranferprofile_withchecksum(self,profilename,remark,validprfix,validextention,clickmodification):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_send_keys(self.PROFILENAME,profilename)
        self.do_click(self.OVERWRITE)
        self.do_click(self.OVERWRITEVALUE)
        self.do_send_keys(self.REMARK,remark)
        self.do_send_keys(self.VALIDPREFIX,validprfix)
        self.do_send_keys(self.VALIDEXTENTION,validextention)
        self.do_send_keys(self.CHECKFILEMODIFICATION,clickmodification)
        self.do_click(self.TRANFERVALIDATION)
        self.do_click(self.VERIFYCHECKSUM)
        self.do_click(self.VERIFYCHECKSUMVALUE)
        self.do_click(self.CHECKSUM)
        time.sleep(1)
        self.do_click(self.CHECKSUMVALUE)
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)
        
    def add_tranferprofile_withtranferfail(self,profilename,remark,validprfix,validextention,clickmodification):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_send_keys(self.PROFILENAME,profilename)
        self.do_click(self.OVERWRITE)
        self.do_click(self.OVERWRITEVALUE)
        self.do_send_keys(self.REMARK,remark)
        self.do_send_keys(self.VALIDPREFIX,validprfix)
        self.do_send_keys(self.VALIDEXTENTION,validextention)
        self.do_send_keys(self.CHECKFILEMODIFICATION,clickmodification)
        self.do_click(self.TRANFERVALIDATION)
        self.do_click(self.VERIFYCHECKSUM)
        self.do_click(self.VERIFYCHECKSUMVALUE)
        time.sleep(2)
        self.do_click(self.CHECKSUM)
        time.sleep(2)
        self.do_click(self.CHECKSUMVALUE)
        time.sleep(2)
        self.do_click(self.TRANSFERFAIL)
        time.sleep(2)
        self.do_click(self.TRANSFERFAILVALUE)
        time.sleep(2)
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)       
         
    def add_tranferprofile_withtranferfailvalue (self,profilename,remark,validprfix,validextention,clickmodification,tranfervalue):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_send_keys(self.PROFILENAME,profilename)
        self.do_click(self.OVERWRITE)
        self.do_click(self.OVERWRITEVALUE)
        self.do_send_keys(self.REMARK,remark)
        self.do_send_keys(self.VALIDPREFIX,validprfix)
        self.do_send_keys(self.VALIDEXTENTION,validextention)
        self.do_send_keys(self.CHECKFILEMODIFICATION,clickmodification)
        self.do_click(self.TRANFERVALIDATION)
        self.do_click(self.VERIFYCHECKSUM)
        self.do_click(self.VERIFYCHECKSUMVALUE)
        self.do_click(self.CHECKSUM)
        time.sleep(1)
        self.do_click(self.CHECKSUMVALUE)
        self.do_click(self.TRANSFERFAIL)
        time.sleep(1)
        self.do_click(self.TRANSFERFAILVALUE)
        self.do_send_keys(self.TRANSFERFAIL_VALUE,tranfervalue)
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)         
        
    def add_tranferprofile_withretrywaittime (self,profilename,remark,validprfix,validextention,clickmodification,tranfervalue,retrywaittime):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_send_keys(self.PROFILENAME,profilename)
        self.do_click(self.OVERWRITE)
        self.do_click(self.OVERWRITEVALUE)
        self.do_send_keys(self.REMARK,remark)
        self.do_send_keys(self.VALIDPREFIX,validprfix)
        self.do_send_keys(self.VALIDEXTENTION,validextention)
        self.do_send_keys(self.CHECKFILEMODIFICATION,clickmodification)
        self.do_click(self.TRANFERVALIDATION)
        self.do_click(self.VERIFYCHECKSUM)
        self.do_click(self.VERIFYCHECKSUMVALUE)
        self.do_click(self.CHECKSUM)
        time.sleep(1)
        self.do_click(self.CHECKSUMVALUE)
        self.do_click(self.TRANSFERFAIL)
        time.sleep(2)
        self.do_click(self.TRANSFERFAILVALUE)
        self.do_send_keys(self.TRANSFERFAIL_VALUE,tranfervalue)
        self.do_send_keys(self.RETRYWAITTIME,retrywaittime)
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)
        
    def add_tranferprofile_withtransferprotocolr (self,profilename,remark,validprfix,validextention,clickmodification,tranfervalue,retrywaittime):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_send_keys(self.PROFILENAME,profilename)
        self.do_click(self.OVERWRITE)
        self.do_click(self.OVERWRITEVALUE)
        self.do_send_keys(self.REMARK,remark)
        self.do_send_keys(self.VALIDPREFIX,validprfix)
        self.do_send_keys(self.VALIDEXTENTION,validextention)
        self.do_send_keys(self.CHECKFILEMODIFICATION,clickmodification)
        self.do_click(self.TRANFERVALIDATION)
        self.do_click(self.VERIFYCHECKSUM)
        self.do_click(self.VERIFYCHECKSUMVALUE)
        self.do_click(self.CHECKSUM)
        time.sleep(1)
        self.do_click(self.CHECKSUMVALUE)
        self.do_click(self.TRANSFERFAIL)
        time.sleep(2)
        self.do_click(self.TRANSFERFAILVALUE)
        self.do_send_keys(self.TRANSFERFAIL_VALUE,tranfervalue)
        self.do_send_keys(self.RETRYWAITTIME,retrywaittime)
        self.do_click(self.TRANSFERMEC)
        self.do_click(self.TRANSFERPROTOCOL)
        time.sleep(1)
        self.do_click(self.TRANSFERPROTOCOLVALUE)
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)
    def add_tranferprofile_save (self,profilename,remark,validprfix,validextention,clickmodification,tranfervalue,retrywaittime,uploadspeed):
        time.sleep(2)
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        self.do_click(self.ADDNEW)
        self.do_send_keys(self.PROFILENAME,profilename)
        self.do_click(self.OVERWRITE)
        self.do_click(self.OVERWRITEVALUE)
        self.do_send_keys(self.REMARK,remark)
        self.do_send_keys(self.VALIDPREFIX,validprfix)
        self.do_send_keys(self.VALIDEXTENTION,validextention)
        self.do_send_keys(self.CHECKFILEMODIFICATION,clickmodification)
        self.do_click(self.TRANFERVALIDATION)
        self.do_click(self.VERIFYCHECKSUM)
        self.do_click(self.VERIFYCHECKSUMVALUE)
        self.do_click(self.CHECKSUM)
        time.sleep(1)
        self.do_click(self.CHECKSUMVALUE)
        self.do_click(self.TRANSFERFAIL)
        time.sleep(2)
        self.do_click(self.TRANSFERFAILVALUE)
        self.do_send_keys(self.TRANSFERFAIL_VALUE,tranfervalue)
        self.do_send_keys(self.RETRYWAITTIME,retrywaittime)
        self.do_click(self.TRANSFERMEC)
        self.do_click(self.TRANSFERPROTOCOL)
        time.sleep(1)
        self.do_click(self.TRANSFERPROTOCOLVALUE)
        self.do_click(self.OPERATIONTYPE)
        time.sleep(1)
        self.do_click(self.OPERATIONTYPEVALUE)
        time.sleep(1)
        print(uploadspeed)
        # print(UPLOADSPEED)
        self.do_send_keys(self.DOWNLOADSPEED,uploadspeed)        
        self.do_click(self.SAVEBUTON)
        time.sleep(2)
        if self.is_visible(self.ALERT_MESSAGE):
            return self.get_element_text(self.ALERT_MESSAGE)
        
    def update_data(self,profilename):
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        if self.is_visible(self.UPDATEDATA):
            if(self.get_element_text(self.UPDATEDATA)=="automationtesting"):
                self.do_click(self.UPDATEDATA)
                self.do_send_keys(self.PROFILENAME,profilename)
                self.do_click(self.UPDATEDATA_BUTTON)
                time.sleep(1)
                if(self.get_element_text(self.UPDATEDATA_NEW)=="automationtestingupdate"):
                    if self.is_visible(self.ALERT_MESSAGE):
                        return self.get_element_text(self.ALERT_MESSAGE)
                        #time.sleep(5)        

    def delete_data(self):
        self.do_click(self.PROFILEBUTTON)
        self.do_click(self.TRANFERTABBUTTON)
        if self.is_visible(self.UPDATEDATA_NEW):
            if(self.get_element_text(self.UPDATEDATA_NEW)=="automationtestingupdate"):
                time.sleep(5)
                self.do_click(self.DELETEBUTTON)
                self.do_click(self.YESBUTTON)
                if self.is_visible(self.ALERT_MESSAGE):
                    return self.get_element_text(self.ALERT_MESSAGE)